language: node_js
sudo: false

node_js:
  - "node"

install:
  - npm ci

script:
  - npm run compile
  - npm test

after_success:
  - npm install -g vsce
  - npm run package

deploy:
  - provider: script
    skip_cleanup: true
    script: vsce publish -p $VSC_KEY --packagePath client/*.vsix
    on:
      branch: travis-deploy

notifications:
  email:
    recipients:
      - juan.cruz@ibm.com
      - yeray.darias@ibm.com
    on_success: change
    on_failure: always