language: node_js
sudo: false

node_js:
  - "9.5.0"

before_install:
  - npm install -g vsce

install:
  - npm install

jobs: 
  include:
    - stage: compile
      script: npm run compile
    - stage: test
      script: npm test
    - stage: lint
      script: npm run lint

notifications:
  email:
    recipients:
      - juan.cruz@ibm.com
      - yeray.darias@ibm.com
    on_success: change
    on_failure: always