language: node_js
sudo: false

node_js:
  - "node"

install:
  - npm ci

jobs: 
  include:
    - stage: compile
      script: npm run compile
    - stage: test
      script: npm test

notifications:
  email:
    recipients:
      - juan.cruz@ibm.com
      - yeray.darias@ibm.com
    on_success: change
    on_failure: always