language: node_js
sudo: false

node_js:
  - "9.5.0"

jobs: 
  include:
    - stage: install
      script: npm install
    - stage: compile
      script: npm run compile
    - stage: test
      script: npm test

notifications:
  email:
    recipients:
      - juan.cruz@ibm.com
      - yeray.darias@ibm.com
    on_success: change
    on_failure: always