language: node_js
sudo: false

node_js:
  - "9.5.0"

before_install:
  - npm install -g npm@6.1.0

install:
  - npm install

script:
  - npm run compile
  - npm test

before_deploy: 
  - npm install -g vsce
  - npm run package

deploy:
  - provider: script
    skip_cleanup: true
    script: 
      - cd client
      - vsce publish -p $VSC_KEY
      - cd ..
    on:
      branch: travis-deploy

notifications:
  email:
    recipients:
      - juan.cruz@ibm.com
      - yeray.darias@ibm.com
    on_success: never
    on_failure: always