language: node_js
sudo: false

node_js:
  - "9.5.0"

install:
  - npm install

jobs:
  include:
    - stage: build
      script: npm run compile
    - stage: test
      script: npm test
    - stage: static-analysis
      script: npm run lint

notifications:
  email:
    recipients:
      - juan.cruz@ibm.com
      - yeray.darias@ibm.com
    on_success: change
    on_failure: always