language: node_js
sudo: false

node_js:
  - "node"

before_install:
  - npm install -g vsce

install:
  - npm ci

jobs: 
  include:
    - stage: compile
      script: npm run compile
    - stage: test
      script: npm test
    - stage: deploy
      if: branch = travis-deploy AND tag =~ ^v\d\.\d\.\d$
      script: vsce publish -p $VSC_KEY

notifications:
  email:
    recipients:
      - juan.cruz@ibm.com
      - yeray.darias@ibm.com
    on_success: change
    on_failure: always