language: node_js

node_js:
  - "9.5.0"

os:
  - linux

dist: trusty

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install:
  - npm install -g vsce
  - npm install

script:
  - npm run compile
  - npm test

before_deploy: 
  - npm run package

deploy:
  - provider: script
    skip_cleanup: true
    script: 
      - cd client
      - vsce publish -p $VSC_KEY
      - cd ..
    on:
      branch: travis-deploy

notifications:
  email:
    recipients:
      - juan.cruz@ibm.com
      - yeray.darias@ibm.com
    on_success: never
    on_failure: always