language: node_js

sudo: required

node_js:
  - "9.5.0"

os:
  - linux

dist: trusty

install:
  - npm install -g vsce
  - npm install

script:
  - npm run compile
  - npm test
  - npm run package

deploy:
  - provider: script
    skip_cleanup: true
    script: 
      - cd client
      - vsce publish -p $VSC_KEY
      - cd ..
    on:
      branch: travis-deploy

notifications:
  email:
    recipients:
      - juan.cruz@ibm.com
      - yeray.darias@ibm.com
    on_success: never
    on_failure: always